# Results

```{r}
# Import All Necessary Libraries
library(tidyverse)
library(patchwork)
library(repr)
library(ggnewscale)
library(RColorBrewer)
library(Lock5withR)
library(naniar)
library(ggplot2)
library(ggplot2)
library(gganimate)


# Import Helper Libraries
source("R_Scripts/plot_missing.R")
source("R_Scripts/readJar.R")
source("R_Scripts/readGVA.R")
```


```{r cleveland}
df <- read_csv("data/processed/ucr/annual_hc_count_by_place.csv",show_col_types = FALSE)
df$min <- apply(df[2:11], MARGIN =  1, FUN = min, na.rm = T)
df$max <- apply(df[2:11], MARGIN =  1, FUN = max, na.rm = T)
#df$Total <- rowSums(df[ , c(2,3,4,5,6,7,8,9,10,11)], na.rm=TRUE)
filter(df, Place != "Other/unknown") %>% mutate(Place = fct_reorder(Place, max, .desc = FALSE)) %>% ggplot() +  geom_point(aes(min, Place, color = "Min")) + 
  geom_point(aes(max, Place, color = "Max")) +
  theme(plot.title = element_text(hjust = 0.5), axis.line = element_line(colour = "black"))+
  ggtitle("Maximum and Minimum Incidents w.r.t. Location")+
  xlab('Incidents') + 
  ylab('Location') 
```
```{r type}
df <- read_csv("data/processed/ucr/FBI_UCR_TABLE2_Incidents.csv",show_col_types = FALSE)
df2 <- df[-c(1,2, 8,15, 16), ]
df2 %>% 
  pivot_longer(., -Crime, values_to = "Incidents", names_to = "Year") %>% 
  ggplot(., aes(x=Year, y=Incidents, group=Crime)) +
  geom_line(aes(color=Crime)) + geom_point(size =0.5) +
  geom_vline(xintercept = 8, size =0.5, color = 'brown3')+
  geom_vline(xintercept = 4, size =0.5, color = 'deepskyblue4')+
  annotate("text", x = 2.8, y = 3000, label = "Obama Re-elected", size =3)+
  annotate("text", x = 9, y = 3000, label = "Trump elected", size =3)+
  ggtitle("Incidents vs Years (by Types of Crime)")
  

```
```{r sumtype}
df <- read_csv("data/processed/ucr/FBI_UCR_TABLE2_Incidents.csv",show_col_types = FALSE)
df2 <- df[c(1,2, 8, 16), ]
df2 %>% 
  pivot_longer(., -Crime, values_to = "Incidents", names_to = "Year") %>% 
  ggplot(., aes(x=Year, y=Incidents, group=Crime)) +
  geom_line(aes(color=Crime)) + geom_point(size =0.5) +
  geom_vline(xintercept = 8, size =0.5, color = 'brown3')+
  geom_vline(xintercept = 4, size =0.5, color = 'deepskyblue4')+
  annotate("text", x = 2.8, y = 7000, label = "Obama Re-elected", size =3)+
  annotate("text", x = 9, y = 7000, label = "Trump elected", size =3)+
  ggtitle("Incidents vs Years (Aggregated types)")

```

```{r age}
df <- read_csv("data/processed/ucr/annual_offenders_by_age.csv",show_col_types = FALSE)
df2 <- subset(df,select = -c(2,3,4))
df2 <-pivot_longer(df2, -`Age Category`, values_to = "Incidents", names_to = "Year") 

ggplot(df2, aes(fill=`Age Category`, y=Incidents, x=Year)) + 
    geom_bar(position="dodge", stat="identity")+
    ggtitle("Incidents through Years w.r.t Age Category")
```

```{r amfm}
df <- read_csv("data/processed/ucr/FBI_UCR_TABLE1.csv",show_col_types = FALSE)
df2 <- filter(df, `Bias motivation` %in% c("Anti-Male","Anti-Female"))

#df2 <- subset(df,select = -c(2,3,4))
#df2 <-pivot_longer(df2, -`Age Category`, values_to = "Incidents", names_to = "Year") 
#df2
ggplot(df2, aes(x = Year, fill = `Bias motivation`,
                 y = ifelse(test = `Bias motivation` == "Anti-Male",
                           yes = -Incidents, no = Incidents))) + 
  geom_bar(stat = "identity", width = 0.5) +
 scale_y_continuous(labels = abs, limits = max(df2$Incidents) * c(-1,1)) +
  coord_flip()+ylab("Anti-Male v Anti Female") +xlab("Year") +
   scale_x_continuous(breaks = c(2013, 2014,2015,2016,2017,2018,2019))+
   ggtitle("Anti-Male vs Anti-Female Incidents through Years")
```


```{r grouped}
df <- read_csv("data/processed/ucr/FBI_UCR_TABLE1.csv",show_col_types = FALSE)
df$`Bias motivation`[df$`Bias motivation`=="Anti-Black or African American"]<-"Anti-Black"
df$`Bias motivation`[df$`Bias motivation`=="Anti-American Indian or Alaska Native"]<-"Anti-American Indian/Alaskan Native"
df$`Bias motivation`[df$`Bias motivation`=="Anti-Asian/Pacific Islander"]<-"Anti-Asian"


df2 <- filter(df, `Bias motivation` %in% c("Anti-White","Anti-Black","Anti-Black or African American","Anti-American Indian/Alaskan Native","Anti-Asian","Anti-Multiple Races, Group"))

#
#df2 <- subset(df2,select = -c(3))
#df2 <-pivot_wider(df2, values_from = "Incidents", names_from = "Year") 

ggplot(df2, aes(fill=`Bias motivation`, y=Incidents, x=Year)) + 
    geom_bar(position="dodge", stat="identity")+
     scale_x_continuous(breaks = c(2010,2011,2012,2013, 2014,2015,2016,2017,2018,2019))+
  ggtitle("Incidents through years w.r.t Race-Bias")

```

### Adding my Plots (Vijay)

JAR BoxPlot 

```{r}
source("R_Scripts/JAR-BoxPlots-Race.R")

JarBoxPlots_RacePLot()

```
```{r}
source("R_Scripts/JAR-BoxPlots.R")
JarBoxPlots()
```

```{r}
source("R_Scripts/JAR-BoxPlots.R")
JarBoxPlots()
```

```{r}
source("R_Scripts/JAR-HeatMap-Gender.R")
JarHeatMap_GenderPlot()
```

```{r}
source("R_Scripts/JAR-HeatMap-Race.R")
Jar_Heatmap_plot()
```

```{r}
source("R_Scripts/JAR-RadarGraphs-Race.R")
JarRadarRace()
```

```{r}
source("R_Scripts/JAR-RadarGraphs.R")
JarGenderRadar()
```

```{r}
source("R_Scripts/GVA-Animation.R")
GVA_Animation()

```

```{r}
source("R_Scripts/GVA-ParallelPlot.R")
GVA_ParallelPlot()
```

```{r}
source("R_Scripts/US-StateMapPlot.R")
GunViolenceStateMap()
```


```{r}
source("R_Scripts/Table8Script.R")
HCtable8_plot()
```

```{r}
source("R_Scripts/Table10-A.R")
HCtable10_HeatMap()
```

```{r}
source("R_Scripts/Table10.R")
HCtable10_plot()
```



