# GVA Map Plot 
GunViolenceStateMap<- function() {

library(usmap)
library(ggplot2)

library(hrbrthemes)
library(GGally)
library(viridis)
source("R_Scripts/readGVA.R")


GVAList = readGVA()
Gidf = data.frame(GVAList[2])
Gddf = data.frame(GVAList[3])
Gmdf = data.frame(GVAList[1])



Gmdf$IncidentDate <- as.Date(Gmdf$IncidentDate,format="%B%d,%Y")
Gmdf$Year <- format(Gmdf$IncidentDate, format = "%Y")
Gmdf$Month <-format(Gmdf$IncidentDate, format = "%b")

Gmdf <- Gmdf %>% group_by(Year,State) %>% summarise(InjuredCount  = sum(Injured,Killed)) 

Gmdf <- rename_with(Gmdf,tolower)
Gmdf$year <- as.numeric(Gmdf$year)

Gmdf <- Gmdf %>% ungroup()

Gmdf <- Gmdf %>% add_row(year = 2014,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Delaware", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Iowa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Idaho", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Kansas", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Montana", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Nebraska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="West Virginia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2014,state ="Wyoming", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Alaska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Idaho", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Maine", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Utah", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="West Virginia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2015,state ="Wyoming", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Alaska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Iowa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Idaho", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Maine", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Montana", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Nebraska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Rhode Island", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="South Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Utah", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2016,state ="Wyoming", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Alaska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Idaho", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Nebraska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Oregon", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Rhode Island", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="South Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="West Virginia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2017,state ="Wyoming", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Alaska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Iowa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Idaho", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Maine", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Montana", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Oregon", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Rhode Island", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="South Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="West Virginia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2018,state ="Wyoming", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Alaska", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Idaho", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Maine", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Rhode Island", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="South Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Utah", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2019,state ="West Virginia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Montana", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="New Hampshire", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Rhode Island", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2020,state ="Wyoming", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="American Samoa", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="District ", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="of Columbia", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Guam", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Hawaii", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Maine", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Montana", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="North Dakota", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Puerto Rico", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Virgin Islands", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Vermont", injuredcount = 0)
Gmdf <- Gmdf %>% add_row(year = 2021,state ="Wyoming", injuredcount = 0)

plot_usmap(data = Gmdf, values = "injuredcount", color = "black") + 
  scale_fill_continuous(low = "green", high = "red",name = "Number of Injuries", label = scales::comma) + 
  theme(legend.position = "right") +
  transition_states(year) +
  ggtitle('Mass Shootings across America in Year {closest_state}')


}